"""
One-shot migration: shop.db (SQLite) -> Supabase PostgreSQL.
Run: python scripts/migrate_sqlite_to_supabase.py

Uses CREATE IF NOT EXISTS + DELETE instead of DROP TABLE so the migration does not
need ACCESS EXCLUSIVE locks (Vercel can keep serving SELECTs while rows are replaced).
"""
from __future__ import annotations

import sqlite3
import sys

import psycopg2
from psycopg2.extras import execute_batch

SQLITE_PATH = r"c:\Users\William\Documents\.Personal Documents\.Winter 2026\Junior Core\IS 455\Deployment\VibeCodeAttempt2\shop.db"

DATABASE_URL = (
    "postgresql://postgres.sbltgtzecialnwsdvxfa:parkerracheljoshuawilliam@"
    "aws-1-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require"
)

SCHEMA_STATEMENTS = [
    """
CREATE TABLE IF NOT EXISTS customers (
  customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  gender TEXT NOT NULL,
  birthdate TEXT NOT NULL,
  created_at TEXT NOT NULL,
  city TEXT,
  state TEXT,
  zip_code TEXT,
  customer_segment TEXT,
  loyalty_tier TEXT,
  is_active INTEGER NOT NULL DEFAULT 1
)
""",
    """
CREATE TABLE IF NOT EXISTS products (
  product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT NOT NULL UNIQUE,
  product_name TEXT NOT NULL,
  category TEXT NOT NULL,
  price DOUBLE PRECISION NOT NULL,
  cost DOUBLE PRECISION NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1
)
""",
    """
CREATE TABLE IF NOT EXISTS orders (
  order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customers(customer_id),
  order_datetime TEXT NOT NULL,
  billing_zip TEXT,
  shipping_zip TEXT,
  shipping_state TEXT,
  payment_method TEXT NOT NULL,
  device_type TEXT NOT NULL,
  ip_country TEXT NOT NULL,
  promo_used INTEGER NOT NULL DEFAULT 0,
  promo_code TEXT,
  order_subtotal DOUBLE PRECISION NOT NULL,
  shipping_fee DOUBLE PRECISION NOT NULL,
  tax_amount DOUBLE PRECISION NOT NULL,
  order_total DOUBLE PRECISION NOT NULL,
  risk_score DOUBLE PRECISION NOT NULL,
  is_fraud INTEGER NOT NULL DEFAULT 0,
  predicted_is_fraud INTEGER
)
""",
    """
CREATE TABLE IF NOT EXISTS order_items (
  order_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES orders(order_id),
  product_id INTEGER NOT NULL REFERENCES products(product_id),
  quantity INTEGER NOT NULL,
  unit_price DOUBLE PRECISION NOT NULL,
  line_total DOUBLE PRECISION NOT NULL
)
""",
    """
CREATE TABLE IF NOT EXISTS product_reviews (
  review_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES customers(customer_id),
  product_id INTEGER NOT NULL REFERENCES products(product_id),
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  review_datetime TEXT NOT NULL,
  review_text TEXT,
  UNIQUE(customer_id, product_id)
)
""",
    """
CREATE TABLE IF NOT EXISTS shipments (
  shipment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL UNIQUE REFERENCES orders(order_id),
  ship_datetime TEXT NOT NULL,
  carrier TEXT NOT NULL,
  shipping_method TEXT NOT NULL,
  distance_band TEXT NOT NULL,
  promised_days INTEGER NOT NULL,
  actual_days INTEGER NOT NULL,
  late_delivery INTEGER NOT NULL DEFAULT 0
)
""",
]

INDEX_STATEMENTS = [
    "CREATE INDEX IF NOT EXISTS idx_items_order ON order_items(order_id)",
    "CREATE INDEX IF NOT EXISTS idx_items_product ON order_items(product_id)",
    "CREATE INDEX IF NOT EXISTS idx_orders_customer ON orders(customer_id)",
    "CREATE INDEX IF NOT EXISTS idx_orders_datetime ON orders(order_datetime)",
    "CREATE INDEX IF NOT EXISTS idx_reviews_customer ON product_reviews(customer_id)",
    "CREATE INDEX IF NOT EXISTS idx_reviews_product ON product_reviews(product_id)",
    "CREATE INDEX IF NOT EXISTS idx_shipments_late ON shipments(late_delivery)",
]

# Child tables first (FK-safe)
DELETE_STATEMENTS = [
    "DELETE FROM order_items",
    "DELETE FROM product_reviews",
    "DELETE FROM shipments",
    "DELETE FROM orders",
    "DELETE FROM customers",
    "DELETE FROM products",
]


def restart_identity(cur, table: str, pk: str) -> None:
    allowed = {
        ("customers", "customer_id"),
        ("products", "product_id"),
        ("orders", "order_id"),
        ("order_items", "order_item_id"),
        ("product_reviews", "review_id"),
        ("shipments", "shipment_id"),
    }
    if (table, pk) not in allowed:
        raise ValueError("invalid table for identity restart")
    cur.execute(f'SELECT COALESCE(MAX("{pk}")::bigint, 0) FROM "{table}"')
    m = int(cur.fetchone()[0])
    nxt = max(m + 1, 1)
    cur.execute(f'ALTER TABLE "{table}" ALTER COLUMN "{pk}" RESTART WITH {nxt}')


def batch_insert(cur, sql_stmt: str, rows: list[tuple]) -> None:
    if not rows:
        return
    execute_batch(cur, sql_stmt, rows, page_size=500)


def main() -> None:
    lite = sqlite3.connect(SQLITE_PATH)
    lite.row_factory = sqlite3.Row

    pg = psycopg2.connect(DATABASE_URL, connect_timeout=120)
    pg.autocommit = True
    cur = pg.cursor()
    cur.execute("SET statement_timeout = 0")

    def log(msg: str) -> None:
        print(msg, flush=True)

    log("Ensuring schema (CREATE IF NOT EXISTS)...")
    for stmt in SCHEMA_STATEMENTS:
        cur.execute(stmt.strip())
    cur.execute(
        "ALTER TABLE orders ADD COLUMN IF NOT EXISTS predicted_is_fraud INTEGER"
    )
    for stmt in INDEX_STATEMENTS:
        cur.execute(stmt)

    log("Clearing existing rows (DELETE, no DROP)...")
    for stmt in DELETE_STATEMENTS:
        cur.execute(stmt)

    cur.close()
    pg.close()

    pg = psycopg2.connect(DATABASE_URL, connect_timeout=120)
    pg.autocommit = False
    cur = pg.cursor()
    cur.execute("SET statement_timeout = 0")

    log("Loading customers...")
    rows = lite.execute("SELECT * FROM customers ORDER BY customer_id").fetchall()
    batch_insert(
        cur,
        """
        INSERT INTO customers (
          customer_id, full_name, email, gender, birthdate, created_at,
          city, state, zip_code, customer_segment, loyalty_tier, is_active
        ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """,
        [tuple(r) for r in rows],
    )
    restart_identity(cur, "customers", "customer_id")
    pg.commit()

    log("Loading products...")
    rows = lite.execute("SELECT * FROM products ORDER BY product_id").fetchall()
    batch_insert(
        cur,
        """
        INSERT INTO products (
          product_id, sku, product_name, category, price, cost, is_active
        ) VALUES (%s,%s,%s,%s,%s,%s,%s)
        """,
        [tuple(r) for r in rows],
    )
    restart_identity(cur, "products", "product_id")
    pg.commit()

    log("Loading orders...")
    rows = lite.execute("SELECT * FROM orders ORDER BY order_id").fetchall()
    batch_insert(
        cur,
        """
        INSERT INTO orders (
          order_id, customer_id, order_datetime, billing_zip, shipping_zip,
          shipping_state, payment_method, device_type, ip_country, promo_used,
          promo_code, order_subtotal, shipping_fee, tax_amount, order_total,
          risk_score, is_fraud, predicted_is_fraud
        ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,NULL)
        """,
        [tuple(r) for r in rows],
    )
    restart_identity(cur, "orders", "order_id")
    pg.commit()

    log("Loading order_items...")
    rows = lite.execute("SELECT * FROM order_items ORDER BY order_item_id").fetchall()
    batch_insert(
        cur,
        """
        INSERT INTO order_items (
          order_item_id, order_id, product_id, quantity, unit_price, line_total
        ) VALUES (%s,%s,%s,%s,%s,%s)
        """,
        [tuple(r) for r in rows],
    )
    restart_identity(cur, "order_items", "order_item_id")
    pg.commit()

    log("Loading product_reviews...")
    rows = lite.execute("SELECT * FROM product_reviews ORDER BY review_id").fetchall()
    batch_insert(
        cur,
        """
        INSERT INTO product_reviews (
          review_id, customer_id, product_id, rating, review_datetime, review_text
        ) VALUES (%s,%s,%s,%s,%s,%s)
        """,
        [tuple(r) for r in rows],
    )
    restart_identity(cur, "product_reviews", "review_id")
    pg.commit()

    log("Loading shipments...")
    rows = lite.execute("SELECT * FROM shipments ORDER BY shipment_id").fetchall()
    batch_insert(
        cur,
        """
        INSERT INTO shipments (
          shipment_id, order_id, ship_datetime, carrier, shipping_method,
          distance_band, promised_days, actual_days, late_delivery
        ) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s)
        """,
        [tuple(r) for r in rows],
    )
    restart_identity(cur, "shipments", "shipment_id")
    pg.commit()
    cur.close()
    pg.close()
    lite.close()

    log("Done. Row counts should match SQLite:")
    log("  customers 250, products 100, orders 5000, order_items 15022,")
    log("  product_reviews 3000, shipments 5000")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
